/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setSize(1000, 600);
        setLocationRelativeTo(this); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MMenu = new javax.swing.JMenu();
        MKlien = new javax.swing.JMenuItem();
        MBarang = new javax.swing.JMenuItem();
        MSuratJalan = new javax.swing.JMenuItem();
        TInvoice = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MLaporan = new javax.swing.JMenu();
        LSuratJalan = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MMenu.setText("File Master");
        MMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMenuActionPerformed(evt);
            }
        });

        MKlien.setText("Entry Klien");
        MKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKlienActionPerformed(evt);
            }
        });
        MMenu.add(MKlien);

        MBarang.setText("Entry Barang");
        MBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBarangActionPerformed(evt);
            }
        });
        MMenu.add(MBarang);

        MSuratJalan.setText("Entry Surat Jalan");
        MSuratJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSuratJalanActionPerformed(evt);
            }
        });
        MMenu.add(MSuratJalan);

        jMenuBar1.add(MMenu);

        TInvoice.setText("Transaksi");

        jMenuItem2.setText("Entry Invoice");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        TInvoice.add(jMenuItem2);

        jMenuItem1.setText("Entry Pra Invoive");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        TInvoice.add(jMenuItem1);

        jMenuBar1.add(TInvoice);

        MLaporan.setText("Laporan");

        LSuratJalan.setText("Laporan Invoice");
        LSuratJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSuratJalanActionPerformed(evt);
            }
        });
        MLaporan.add(LSuratJalan);

        jMenuItem3.setText("Laporan Pra Invoice");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MLaporan.add(jMenuItem3);

        jMenuItem4.setText("Laporan Pengiriman");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MLaporan.add(jMenuItem4);

        jMenuBar1.add(MLaporan);

        MExit.setText("Exit Program");
        MExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(MExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MSuratJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSuratJalanActionPerformed
        // TODO add your handling code here:
        View.MSuratJalan p = new View.MSuratJalan();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MSuratJalanActionPerformed

    private void MExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MExitMouseClicked
            // TODO add your handling code here:
        int keluar = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0);
            dispose();
        }
    }//GEN-LAST:event_MExitMouseClicked

    private void MMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMenuActionPerformed

    private void MBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBarangActionPerformed
        // TODO add your handling code here:
        View.MBarang p = new View.MBarang();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MBarangActionPerformed

    private void MKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKlienActionPerformed
        // TODO add your handling code here:
        View.MKlien p = new View.MKlien();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MKlienActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        View.TPraInvoice p = new View.TPraInvoice();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void LSuratJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSuratJalanActionPerformed
        // TODO add your handling code here:
        View.LInvoice p = new View.LInvoice();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_LSuratJalanActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        View.TInvoice p = new View.TInvoice();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        View.LSuratJalan p = new View.LSuratJalan();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        View.LPraInvoice p = new View.LPraInvoice();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LSuratJalan;
    private javax.swing.JMenuItem MBarang;
    private javax.swing.JMenu MExit;
    private javax.swing.JMenuItem MKlien;
    private javax.swing.JMenu MLaporan;
    private javax.swing.JMenu MMenu;
    private javax.swing.JMenuItem MSuratJalan;
    private javax.swing.JMenu TInvoice;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
