/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
 
import Koneksi.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class MKlien extends javax.swing.JFrame { 

    private DefaultTableModel model;
    Connection con;
    Statement st;
    Koneksi kon=new Koneksi();
    String query, tmpID;
    
    /**
     * Creates new form MKlien
     */
    public MKlien() {
        initComponents();
        setLocationRelativeTo(this); 
        
        BuatTabel(); 
        showTabel();
    }

    void Bersih(){
        txtkdklien.setText("");
        txtnmklien.setText("");
        txttelepon.setText("");
        txtalamat.setText("");
        txtkdklien.requestFocus();
    }

    private void BuatTabel(){
        model=new DefaultTableModel();
        model.addColumn("ID Klien");
        model.addColumn("Nama Klien");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
        tblklien.setModel(model);
    }
     
    public void showTabel(){
      removeTable();        
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_klien order by id_klien  asc";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              String a =rs.getString("id_klien");
              String b=rs.getString("nama_klien");
              String c=rs.getString("no_telp"); 
              String d=rs.getString("alamat"); 
              String data[]={a,b,c,d};          
              model.addRow(data);         
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
    
    public void removeTable(){
        try{for(int t=model.getRowCount();t>0;t--) {model.removeRow(0);}
        }catch(Exception ex){ System.out.println(ex);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkdklien = new javax.swing.JTextField();
        txtnmklien = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblklien = new javax.swing.JTable();
        cmdsimpan = new javax.swing.JButton();
        cmdubah = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entry Data Klien");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Kode Klien");

        jLabel3.setText("Nama Klien");

        jLabel4.setText("Telepon");

        jLabel5.setText("Alamat");

        txtnmklien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmklienActionPerformed(evt);
            }
        });

        tblklien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Klien", "Telepon", "Alamat"
            }
        ));
        tblklien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblklienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblklienMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblklien);

        cmdsimpan.setText("SIMPAN");
        cmdsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpanActionPerformed(evt);
            }
        });

        cmdubah.setText("UBAH");
        cmdubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubahActionPerformed(evt);
            }
        });

        cmdhapus.setText("HAPUS");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdbatal.setText("BATAL");
        cmdbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtkdklien)
                            .addComponent(txtnmklien)
                            .addComponent(txttelepon)
                            .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(cmdubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addComponent(txtkdklien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnmklien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan)
                    .addComponent(cmdubah)
                    .addComponent(cmdhapus)
                    .addComponent(cmdbatal))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnmklienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmklienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmklienActionPerformed

    private void cmdsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpanActionPerformed
        // TODO add your handling code here: 
         try{
            kon.QUERY("INSERT INTO tb_klien (id_klien ,nama_klien, no_telp, alamat) VALUES "
                + " ('"+txtkdklien.getText()+"', '"+txtnmklien.getText()+"','"+ txttelepon.getText() +"','"+ txtalamat.getText() +"')","di Simpan");
            
            showTabel();
            Bersih();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Simpan"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdsimpanActionPerformed

    private void cmdubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubahActionPerformed
        // TODO add your handling code here: 
         try{
            kon.QUERY("UPDATE tb_klien SET nama_klien='"+txtnmklien.getText()+"',no_telp='"+ txttelepon.getText() +"',alamat='"+ txtalamat.getText() +"' WHERE id_klien='"+txtkdklien.getText()+"'","di Ubah");
            showTabel();
            Bersih();
            txtkdklien.setEditable(true);
            txtkdklien.requestFocus();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Ubah"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdubahActionPerformed

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed
        // TODO add your handling code here: 
        int hapus = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Hapus Data?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (hapus == JOptionPane.YES_OPTION) {
            try{
                kon.QUERY("DELETE FROM tb_klien WHERE id_klien ='"+txtkdklien.getText()+"'","di Hapus");
                showTabel();
                Bersih();
                txtkdklien.setEditable(true);
                txtkdklien.requestFocus();
            }catch(Exception sqle){
                JOptionPane.showMessageDialog(rootPane,"Data Gagal Simpan"+sqle.getMessage());
            }
        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbatalActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_cmdbatalActionPerformed

    private void tblklienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblklienMouseClicked
        // TODO add your handling code here:
        int baris = tblklien.getSelectedRow();
        txtkdklien.setText(tblklien.getValueAt(baris, 0).toString());
        txtnmklien.setText(tblklien.getValueAt(baris, 1).toString());
        txttelepon.setText(tblklien.getValueAt(baris, 2).toString());
        txtalamat.setText(tblklien.getValueAt(baris, 3).toString());
        txtkdklien.setEditable(false);
        txtnmklien.requestFocus();
    }//GEN-LAST:event_tblklienMouseClicked

    private void tblklienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblklienMousePressed
        // TODO add your handling code here:
        int baris = tblklien.getSelectedRow();
        txtkdklien.setText(tblklien.getValueAt(baris, 0).toString());
        txtnmklien.setText(tblklien.getValueAt(baris, 1).toString());
        txttelepon.setText(tblklien.getValueAt(baris, 2).toString());
        txtalamat.setText(tblklien.getValueAt(baris, 3).toString());
        txtkdklien.setEditable(false);
        txtnmklien.requestFocus();
        
    }//GEN-LAST:event_tblklienMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MKlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JButton cmdubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblklien;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtkdklien;
    private javax.swing.JTextField txtnmklien;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
