/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
 
import Koneksi.Koneksi;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class MSuratJalan extends javax.swing.JFrame { 

    private DefaultTableModel model;
    Connection con;
    Statement st;
    Koneksi kon=new Koneksi();
    String query, tmpID;
    /**
     * Creates new form MSuratJalan
     */
    public MSuratJalan() {
        initComponents();
        setLocationRelativeTo(this); 
        
        BuatTabel(); 
        showTabel();
        
        Date ys=new Date(); // membuat oject ys dari class Date
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy"); 
          
        String tglnow = s.format(ys);
        txttglsuratjalan.setText(tglnow);
         
        txtkadaluarsa.setText(tglnow);
        
        getDataKlien();
    }
    
    void Bersih(){
        txtkdsuratjalan.setText(""); 
        txtkodeklien.setSelectedItem(""); 
        txtnmpenerima.setText("");
        txttujuan.setText("");
        txtketerangan.setText("");
        txtkadaluarsa.setText("");
    }
    
    public void getDataKlien(){      
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_klien";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              txtkodeklien.addItem(rs.getString("id_klien"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }

    private void BuatTabel(){
        model=new DefaultTableModel();
        model.addColumn("No. Surat Jalan");
        model.addColumn("Tgl. Surat Jalan ");
        model.addColumn("Kode Klien");
        model.addColumn("Nama Penerima");
        model.addColumn("Tujuan");
        model.addColumn("Keterangan");
        model.addColumn("Tgl Kadaluarga");
        tblsuratjalan.setModel(model);
    }
     
    public void showTabel(){
      removeTable();        
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_suratjalan a inner join tb_klien b on a.id_klien=b.id_klien order by a.no_suratjalan  asc";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              String a =rs.getString("no_suratjalan");
              String b=rs.getString("tgl_suratjalan");
              String c=rs.getString("id_klien"); 
              String d=rs.getString("nama_klien"); 
              String e=rs.getString("tujuan"); 
              String f=rs.getString("keterangan"); 
              String g=rs.getString("tgl_kadaluarsa"); 
              String data[]={a,b,c,d,e,f,g};          
              model.addRow(data);         
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
    
    public void removeTable(){
        try{for(int t=model.getRowCount();t>0;t--) {model.removeRow(0);}
        }catch(Exception ex){ System.out.println(ex);}
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblanggota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkdsuratjalan = new javax.swing.JTextField();
        txttglsuratjalan = new javax.swing.JTextField();
        txtnmpenerima = new javax.swing.JTextField();
        txttujuan = new javax.swing.JTextField();
        txtkadaluarsa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtketerangan = new javax.swing.JTextArea();
        cmdsimpan = new javax.swing.JButton();
        cmdubah = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsuratjalan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtkodeklien = new javax.swing.JComboBox<>();

        tblanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Anggota", "Nama Anggota", "Alamat", "Telepon"
            }
        ));
        tblanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblanggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblanggota);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRY SURAT JALAN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("No Surat Jalan          :");

        jLabel3.setText("Tanggal Surat Jalan  :");

        jLabel4.setText("Nama Penerima         :");

        jLabel5.setText("Tujuan                      :");

        jLabel6.setText("Keterangan              :");

        jLabel7.setText("Tanggal Kadaluarsa :");

        txtkdsuratjalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkdsuratjalanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkdsuratjalanKeyReleased(evt);
            }
        });

        txttglsuratjalan.setEditable(false);
        txttglsuratjalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttglsuratjalanKeyPressed(evt);
            }
        });

        txtnmpenerima.setEditable(false);

        txttujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttujuanActionPerformed(evt);
            }
        });

        txtketerangan.setColumns(20);
        txtketerangan.setRows(5);
        jScrollPane2.setViewportView(txtketerangan);

        cmdsimpan.setText("SIMPAN");
        cmdsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpanActionPerformed(evt);
            }
        });

        cmdubah.setText("UBAH");
        cmdubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubahActionPerformed(evt);
            }
        });

        cmdhapus.setText("HAPUS");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdbatal.setText("BATAL");
        cmdbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbatalActionPerformed(evt);
            }
        });

        tblsuratjalan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Surat Jalan", "Tanggal Surat Jalan", "Nama Penerima", "Tujuan", "Tanggal Kadaluarsa"
            }
        ));
        tblsuratjalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsuratjalanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblsuratjalan);

        jLabel8.setText("Kode Klien                 :");

        txtkodeklien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Kode Klien -" }));
        txtkodeklien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtkodeklienItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cmdsimpan)
                        .addGap(63, 63, 63)
                        .addComponent(cmdubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(cmdhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(cmdbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttglsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkdsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                    .addComponent(txtkadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnmpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkodeklien, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkdsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttglsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txtkodeklien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtkadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan)
                    .addComponent(cmdubah)
                    .addComponent(cmdhapus)
                    .addComponent(cmdbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(617, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttujuanActionPerformed

    private void cmdsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpanActionPerformed
        // TODO add your handling code here: 
          try{
            kon.QUERY("INSERT INTO tb_suratjalan (no_suratjalan ,tgl_suratjalan, id_klien, tujuan, keterangan, tgl_kadaluarsa) VALUES "
                + " ('"+txtkdsuratjalan.getText()+"', '"+txttglsuratjalan.getText()+"','"+ txtkodeklien.getSelectedItem() +"','"+ txttujuan.getText() +"','"+ txtketerangan.getText() +"','"+ txtkadaluarsa.getText() +"')","di Simpan");
            
            showTabel();
            Bersih();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Simpan"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdsimpanActionPerformed

    private void cmdubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubahActionPerformed
        // TODO add your handling code here: 
         try{
            kon.QUERY("UPDATE tb_suratjalan SET id_klien='"+txtkodeklien.getSelectedItem()+"', tujuan='"+txttujuan.getText()+"', keterangan='"+txtketerangan.getText()+"', tgl_kadaluarsa='"+txtkadaluarsa.getText()+"'  WHERE no_suratjalan='"+txtkdsuratjalan.getText()+"'","di Ubah");
            showTabel();
            Bersih(); 
            txtkdsuratjalan.setEditable(true);
            txtkdsuratjalan.requestFocus();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Ubah"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdubahActionPerformed

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed
        // TODO add your handling code here: 
        int hapus = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Hapus Data ?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (hapus == JOptionPane.YES_OPTION) {
            try{
                kon.QUERY("DELETE FROM tb_suratjalan WHERE no_suratjalan ='"+txtkdsuratjalan.getText()+"'","di Hapus");
                showTabel();
                Bersih(); 
                txtkdsuratjalan.setEditable(true);
                txtkdsuratjalan.requestFocus();
            }catch(Exception sqle){
                JOptionPane.showMessageDialog(rootPane,"Data Gagal di Hapus"+sqle.getMessage());
            }
        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbatalActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_cmdbatalActionPerformed

    private void tblanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblanggotaMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tblanggotaMouseClicked

    private void tblsuratjalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsuratjalanMouseClicked
        // TODO add your handling code here: 
        int baris = tblsuratjalan.getSelectedRow();
        txtkdsuratjalan.setText(tblsuratjalan.getValueAt(baris, 0).toString());
        txttglsuratjalan.setText(tblsuratjalan.getValueAt(baris, 1).toString());
        txtkodeklien.setSelectedItem(tblsuratjalan.getValueAt(baris, 2).toString());
        txtnmpenerima.setText(tblsuratjalan.getValueAt(baris, 3).toString());
        txttujuan.setText(tblsuratjalan.getValueAt(baris, 4).toString());
        txtketerangan.setText(tblsuratjalan.getValueAt(baris, 5).toString());
        txtkadaluarsa.setText(tblsuratjalan.getValueAt(baris, 6).toString());
         
        txtkdsuratjalan.setEditable(false); 
    }//GEN-LAST:event_tblsuratjalanMouseClicked

    private void txtkdsuratjalanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkdsuratjalanKeyReleased
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtkdsuratjalanKeyReleased

    private void txtkdsuratjalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkdsuratjalanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtkdsuratjalan.getText().isEmpty()){
                
            }
            else
                
            this.txttglsuratjalan.requestFocus();
        }
    }//GEN-LAST:event_txtkdsuratjalanKeyPressed

    private void txttglsuratjalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttglsuratjalanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.cmdsimpan.requestFocus();
        }
    }//GEN-LAST:event_txttglsuratjalanKeyPressed

    private void txtkodeklienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtkodeklienItemStateChanged
        // TODO add your handling code here:
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_klien where id_klien='"+txtkodeklien.getSelectedItem()+"'";
         
          ResultSet rs=st.executeQuery(query);
          if(rs.next()){
              txtnmpenerima.setText(rs.getString("nama_klien"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }//GEN-LAST:event_txtkodeklienItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MSuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MSuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MSuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MSuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MSuratJalan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JButton cmdubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblanggota;
    private javax.swing.JTable tblsuratjalan;
    private javax.swing.JTextField txtkadaluarsa;
    private javax.swing.JTextField txtkdsuratjalan;
    private javax.swing.JTextArea txtketerangan;
    private javax.swing.JComboBox<String> txtkodeklien;
    private javax.swing.JTextField txtnmpenerima;
    private javax.swing.JTextField txttglsuratjalan;
    private javax.swing.JTextField txttujuan;
    // End of variables declaration//GEN-END:variables
}
