/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
 
import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class TInvoice extends javax.swing.JFrame { 

    private DefaultTableModel model;
    Connection con;
    Statement st;
    Koneksi kon=new Koneksi();
    String query, tmpID;
    
    /**
     * Creates new form TInvoice
     */
    public TInvoice() {
        initComponents();
        setLocationRelativeTo(this); 
        
        BuatTabel(); 
        showTabel();
        
        Date ys=new Date(); // membuat oject ys dari class Date
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy"); 
          
        String tglnow = s.format(ys);
        txttglinvoice.setText(tglnow);
        
        getDataBarang();
        getDataSuratJalan();
    }

    void Bersih(){
        txtkdinvoice.setText("");
        txtkdsuratjalan.setSelectedItem("- Pilih No Surat Jalan -");
        txttglsuratjalan.setText("");
        txtkdbarang.setSelectedItem("- Pilih Kode Barang -");
        txtnmbarang.setText("");
        txtjumlah.setText("");
    }

    private void BuatTabel(){
        model=new DefaultTableModel();
        model.addColumn("No Invoice");
        model.addColumn("Tgl Invoice");
        model.addColumn("No Surat Jalan");
        model.addColumn("Tgl Surat Jalan");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah");
        tblinvoice.setModel(model);
    }
    
    public void getDataSuratJalan(){      
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_suratjalan";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              txtkdsuratjalan.addItem(rs.getString("no_suratjalan"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
    
    public void getDataBarang(){      
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_barang";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              txtkdbarang.addItem(rs.getString("id_barang"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
     
    public void showTabel(){
      removeTable();        
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_invoice a inner join tb_suratjalan b on a.no_suratjalan=b.no_suratjalan "
                  + " inner join tb_barang c on a.id_barang=c.id_barang order by a.no_invoice  asc";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              String a =rs.getString("no_invoice");
              String b=rs.getString("tgl_invoice");
              String c=rs.getString("no_suratjalan"); 
              String d=rs.getString("tgl_suratjalan"); 
              String e=rs.getString("id_barang");
              String f=rs.getString("nama_barang"); 
              String g=rs.getString("jumlah"); 
              String data[]={a,b,c,d,e,f,g};          
              model.addRow(data);         
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
    
    public void removeTable(){
        try{for(int t=model.getRowCount();t>0;t--) {model.removeRow(0);}
        }catch(Exception ex){ System.out.println(ex);}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtkdinvoice = new javax.swing.JTextField();
        txttglinvoice = new javax.swing.JTextField();
        txttglsuratjalan = new javax.swing.JTextField();
        txtnmbarang = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblinvoice = new javax.swing.JTable();
        cmdsimpan1 = new javax.swing.JButton();
        cmdubah = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();
        txtkdsuratjalan = new javax.swing.JComboBox<>();
        txtkdbarang = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRY INVOICE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("No. Invoice");

        jLabel3.setText("Tgl. Invoive");

        jLabel4.setText("No. Surat Jalan");

        jLabel5.setText("Tgl. Surat Jalan");

        jLabel6.setText("Kode Barang");

        jLabel7.setText("Nama Barang");

        jLabel8.setText("Jumlah");

        txttglinvoice.setEditable(false);
        txttglinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglinvoiceActionPerformed(evt);
            }
        });

        txttglsuratjalan.setEditable(false);

        txtnmbarang.setEditable(false);

        txtjumlah.setEditable(false);
        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });

        tblinvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Invoice", "Tgl. Invoice", "No. Surat Jalan", "Tgl. Surat Jalan", "Kode Barang", "Nama Barang", "Jumlah"
            }
        ));
        tblinvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinvoiceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblinvoice);

        cmdsimpan1.setText("SIMPAN");
        cmdsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpan1ActionPerformed(evt);
            }
        });

        cmdubah.setText("UBAH");
        cmdubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubahActionPerformed(evt);
            }
        });

        cmdhapus.setText("HAPUS");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdbatal.setText("BATAL");
        cmdbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbatalActionPerformed(evt);
            }
        });

        txtkdsuratjalan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih No Surat Jalan -" }));
        txtkdsuratjalan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtkdsuratjalanItemStateChanged(evt);
            }
        });

        txtkdbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Kode Barang -" }));
        txtkdbarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtkdbarangItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdsimpan1)
                        .addGap(73, 73, 73)
                        .addComponent(cmdubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(cmdhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(cmdbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtkdinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttglinvoice)
                                .addComponent(txtnmbarang)
                                .addComponent(txtjumlah)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(txtkdsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtkdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttglsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkdinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttglinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkdsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttglsuratjalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtkdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnmbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan1)
                    .addComponent(cmdubah)
                    .addComponent(cmdhapus)
                    .addComponent(cmdbatal))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttglinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglinvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglinvoiceActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void cmdsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpan1ActionPerformed
        // TODO add your handling code here: 
         try{
            kon.QUERY("INSERT INTO tb_invoice (no_invoice ,tgl_invoice, no_suratjalan, id_barang) VALUES "
                + " ('"+txtkdinvoice.getText()+"', '"+txttglinvoice.getText()+"','"+ txtkdsuratjalan.getSelectedItem() +"','"+ txtkdbarang.getSelectedItem() +"')","di Simpan");
            
            showTabel();
            Bersih();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Simpan"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdsimpan1ActionPerformed

    private void cmdubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubahActionPerformed
        // TODO add your handling code here: 
          try{
            kon.QUERY("UPDATE tb_invoice SET no_suratjalan='"+txtkdsuratjalan.getSelectedItem()+"',id_barang='"+ txtkdbarang.getSelectedItem() +"' WHERE no_invoice='"+txtkdinvoice.getText()+"'","di Ubah");
            showTabel();
            Bersih(); 
            txtkdinvoice.setEditable(true);
            txtkdinvoice.requestFocus();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Ubah"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdubahActionPerformed

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed
        // TODO add your handling code here: 
        int hapus = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Hapus Data?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (hapus == JOptionPane.YES_OPTION) {
            try{
                kon.QUERY("DELETE FROM tb_invoice WHERE no_invoice ='"+txtkdinvoice.getText()+"'","di Hapus");
                showTabel();
                Bersih(); 
                txtkdinvoice.setEditable(true);
                txtkdinvoice.requestFocus();
            }catch(Exception sqle){
                JOptionPane.showMessageDialog(rootPane,"Data Gagal di Hapus"+sqle.getMessage());
            }
        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbatalActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_cmdbatalActionPerformed

    private void tblinvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinvoiceMouseClicked
        // TODO add your handling code here:
        int baris = tblinvoice.getSelectedRow();
        txtkdinvoice.setText(tblinvoice.getValueAt(baris, 0).toString());
        txttglinvoice.setText(tblinvoice.getValueAt(baris, 1).toString());
        txtkdsuratjalan.setSelectedItem(tblinvoice.getValueAt(baris, 2).toString());
        txttglsuratjalan.setText(tblinvoice.getValueAt(baris, 3).toString());
        txtkdbarang.setSelectedItem(tblinvoice.getValueAt(baris, 4).toString());
        txtnmbarang.setText(tblinvoice.getValueAt(baris, 5).toString());
        txtjumlah.setText(tblinvoice.getValueAt(baris, 6).toString());
        txtkdinvoice.setEditable(false);
        
    }//GEN-LAST:event_tblinvoiceMouseClicked

    private void txtkdsuratjalanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtkdsuratjalanItemStateChanged
        // TODO add your handling code here:
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_suratjalan where no_suratjalan='"+txtkdsuratjalan.getSelectedItem()+"'";
         
          ResultSet rs=st.executeQuery(query);
          if(rs.next()){
              txttglsuratjalan.setText(rs.getString("tgl_suratjalan"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }//GEN-LAST:event_txtkdsuratjalanItemStateChanged

    private void txtkdbarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtkdbarangItemStateChanged
        // TODO add your handling code here:
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_barang where id_barang='"+txtkdbarang.getSelectedItem()+"'";
         
          ResultSet rs=st.executeQuery(query);
          if(rs.next()){
              txtnmbarang.setText(rs.getString("nama_barang"));
              txtjumlah.setText(rs.getString("jumlah"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }//GEN-LAST:event_txtkdbarangItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan1;
    private javax.swing.JButton cmdubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblinvoice;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JComboBox<String> txtkdbarang;
    private javax.swing.JTextField txtkdinvoice;
    private javax.swing.JComboBox<String> txtkdsuratjalan;
    private javax.swing.JTextField txtnmbarang;
    private javax.swing.JTextField txttglinvoice;
    private javax.swing.JTextField txttglsuratjalan;
    // End of variables declaration//GEN-END:variables
}
