/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
 
import Koneksi.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class TPraInvoice extends javax.swing.JFrame {

    private DefaultTableModel model;
    Connection con;
    Statement st;
    Koneksi kon=new Koneksi();
    String query, tmpID;
    
    /**
     * Creates new form TPraInvoice
     */
    public TPraInvoice() {
        initComponents();
        setLocationRelativeTo(this);
        
        BuatTabel(); 
        showTabel();
        
        Date ys=new Date(); // membuat oject ys dari class Date
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy"); 
          
        String tglnow = s.format(ys);
        txttglprainvoice.setText(tglnow);
        
        getDataSuratJalan();
    }

    void Bersih(){
        txtkdprainvoice.setText(""); 
        txtkdinvoice.setSelectedItem("");
        txttglinvoice.setText("");
        txtkdprainvoice.requestFocus();
    }

    private void BuatTabel(){
        model=new DefaultTableModel();
        model.addColumn("No. Pra Invoice");
        model.addColumn("Tgl. Pra Invoice");
        model.addColumn("No. Invoice");
        model.addColumn("Tgl Invoice");
        tblprainvoice.setModel(model);
    }
    
    
    public void getDataSuratJalan(){      
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_invoice";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              txtkdinvoice.addItem(rs.getString("no_invoice"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
    
    public void showTabel(){
      removeTable();        
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_prainvoice a inner join tb_invoice b on a.no_invoice=b.no_invoice order by a.no_prainvoice  asc";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              String a =rs.getString("no_prainvoice");
              String b=rs.getString("tgl_prainvoice");
              String c=rs.getString("no_invoice"); 
              String d=rs.getString("tgl_invoice"); 
              String data[]={a,b,c,d};          
              model.addRow(data);         
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }
    
    public void removeTable(){
        try{for(int t=model.getRowCount();t>0;t--) {model.removeRow(0);}
        }catch(Exception ex){ System.out.println(ex);}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkdprainvoice = new javax.swing.JTextField();
        txttglprainvoice = new javax.swing.JTextField();
        txttglinvoice = new javax.swing.JTextField();
        cmdsimpan1 = new javax.swing.JButton();
        cmdubah = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprainvoice = new javax.swing.JTable();
        txtkdinvoice = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN INVOICE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRY DATA PRA-INVOICE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("No. Pra-Invoice");

        jLabel4.setText("Tgl. Pra-Invoice");

        jLabel5.setText("No. Invoice");

        jLabel6.setText("Tgl. Invoice");

        txttglprainvoice.setEditable(false);

        txttglinvoice.setEditable(false);

        cmdsimpan1.setText("SIMPAN");
        cmdsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpan1ActionPerformed(evt);
            }
        });

        cmdubah.setText("UBAH");
        cmdubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubahActionPerformed(evt);
            }
        });

        cmdhapus.setText("HAPUS");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdbatal.setText("BATAL");
        cmdbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbatalActionPerformed(evt);
            }
        });

        tblprainvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Pra-Invoice", "Tgl. Pra-Invoice", "No. Invoice", "Tgl. Invoice"
            }
        ));
        tblprainvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprainvoiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblprainvoice);

        txtkdinvoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih No Invoice -" }));
        txtkdinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdinvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(cmdsimpan1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtkdinvoice, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtkdprainvoice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txttglprainvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(txttglinvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkdprainvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttglprainvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtkdinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttglinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan1)
                    .addComponent(cmdubah)
                    .addComponent(cmdhapus)
                    .addComponent(cmdbatal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setBounds(0, 0, 416, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpan1ActionPerformed
        // TODO add your handling code here: 
        try{
            kon.QUERY("INSERT INTO tb_prainvoice (no_prainvoice ,tgl_prainvoice, no_invoice) VALUES "
                + " ('"+txtkdprainvoice.getText()+"', '"+txttglprainvoice.getText()+"','"+ txtkdinvoice.getSelectedItem()+"')","di Simpan");
            
            showTabel();
            Bersih();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Simpan"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdsimpan1ActionPerformed

    private void cmdubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubahActionPerformed
        // TODO add your handling code here: 
        try{
            kon.QUERY("UPDATE tb_prainvoice SET no_invoice='"+txtkdinvoice.getSelectedItem()+"'  WHERE no_prainvoice='"+txtkdprainvoice.getText()+"'","di Ubah");
            showTabel();
            Bersih();
            txtkdprainvoice.setEditable(true);
            txtkdprainvoice.requestFocus();
        }catch(Exception sqle){
            JOptionPane.showMessageDialog(rootPane,"Data Gagal di Ubah"+sqle.getMessage());
        }
    }//GEN-LAST:event_cmdubahActionPerformed

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed
        // TODO add your handling code here: 
         int hapus = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Hapus Data?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (hapus == JOptionPane.YES_OPTION) {
            try{
                kon.QUERY("DELETE FROM tb_prainvoice WHERE no_prainvoice ='"+txtkdprainvoice.getText()+"'","di Hapus");
                showTabel();
                Bersih();
                txtkdprainvoice.setEditable(true);
                txtkdprainvoice.requestFocus();
            }catch(Exception sqle){
                JOptionPane.showMessageDialog(rootPane,"Data Gagal di Hapus"+sqle.getMessage());
            }
        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbatalActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_cmdbatalActionPerformed

    private void tblprainvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprainvoiceMouseClicked
        // TODO add your handling code here:
        int baris = tblprainvoice.getSelectedRow();
        txtkdprainvoice.setText(tblprainvoice.getValueAt(baris, 0).toString());
        txttglprainvoice.setText(tblprainvoice.getValueAt(baris, 1).toString());
        txtkdinvoice.setSelectedItem(tblprainvoice.getValueAt(baris, 2).toString());
        txttglinvoice.setText(tblprainvoice.getValueAt(baris, 3).toString());
        txtkdprainvoice.setEditable(false);
        txtkdinvoice.requestFocus();
    }//GEN-LAST:event_tblprainvoiceMouseClicked

    private void txtkdinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdinvoiceActionPerformed
        // TODO add your handling code here:
        try{
          con=kon.open();
          st=con.createStatement();
          
          query="SELECT * FROM tb_invoice where no_invoice='"+txtkdinvoice.getSelectedItem()+"'";
         
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              txttglinvoice.setText(rs.getString("tgl_invoice"));
          }
      }catch(SQLException sqle){
          JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
    }//GEN-LAST:event_txtkdinvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPraInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPraInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPraInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPraInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPraInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan1;
    private javax.swing.JButton cmdubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblprainvoice;
    private javax.swing.JComboBox<String> txtkdinvoice;
    private javax.swing.JTextField txtkdprainvoice;
    private javax.swing.JTextField txttglinvoice;
    private javax.swing.JTextField txttglprainvoice;
    // End of variables declaration//GEN-END:variables
}
